/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_purplefrog_speexjni_SpeexDecoder */

#ifndef _Included_com_purplefrog_speexjni_SpeexDecoder
#define _Included_com_purplefrog_speexjni_SpeexDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_purplefrog_speexjni_SpeexDecoder
 * Method:    decode
 * Signature: (I[B)[S
 */
JNIEXPORT jshortArray JNICALL Java_com_purplefrog_speexjni_SpeexDecoder_decode
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     com_purplefrog_speexjni_SpeexDecoder
 * Method:    allocate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_purplefrog_speexjni_SpeexDecoder_allocate
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_purplefrog_speexjni_SpeexDecoder
 * Method:    deallocate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_purplefrog_speexjni_SpeexDecoder_deallocate
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
